### ISSUE TITLE
Deprecated symbols we can remove

### ISSUE THREAD

**Issue by richsalz** [quictls/quictls#122]
I wrote this script:
```
#! /bin/bash

scan() {
    echo ""
    echo "Symbols to remove from $1 deprecation:"
    for I in $( cat util/lib*num | grep IN_$1  | awk '{print $1;}' ) ; do
	cat ../libre-*-syms.list | grep -q $I || echo $I
    done
}

scan 0_9_8
scan 1_0_0
scan 1_1_0
scan 1_2_0
```

The *syms.list files are from LibreSSL.  Here's the output.  Make sense, @botovq ?
```
Symbols to remove from 0_9_8 deprecation:
BN_set_params
BN_get_params

Symbols to remove from 1_0_0 deprecation:

Symbols to remove from 1_1_0 deprecation:
SRP_VBASE_get_by_user
ENGINE_setup_bsd_cryptodev
PKCS12_get_attr
SSLv3_client_method
SSLv3_method
SSL_set_debug
SSLv3_server_method

Symbols to remove from 1_2_0 deprecation:

```

Turns out that BN_{set/get}_params aren't implemented, just listed as "missing" so I added them to #113.

I'll make a PR for the 1.1.0 stuff (the rest of VRP should also go? In a separate PR)

**Comment by botovq** [comment]
One slight problem here is that we never added all the 1.1 API, only those bits that we needed to. That doesn't seem to be problematic in your search, though.

SRP_VBASE_get_by_user
ENGINE_setup_bsd_cryptodev

These two left in the early "Valhalla rampage" in 2014. Nothing seems to be using those per code search, so surely they can go.

`PKCS12_get_attr()` is a weird case, but long story short, I think it can be removed. This first became a compat define aliasing `PKCS12_SAFEBAG_get0_attr()` when Henson made PKCS12  opaque, then it became a function, and then it was deprecated by Caswell two weeks before 1.1.0 was released, so the deprecation only actually happened in 1.1.0a. I find two consumers on [debian][1] (trustedqsl libcrypt-openssl-pkcs12-perl), but they both add a compat define if it's not around.

Regarding SSLv3, we disabled and removed SSLv3 a long time ago (2016ish) and things are able to cope. In fact, we removed support for everything older than (D)TLSv1.2 last summer. I am aware of two cases where that posed a bit of a problem, but I suspect it is harder for you to get away with than it was for us. I heard that BoringSSL won't be able to remove TLSv1.1 anytime soon.

Oh and yes, `SSL_set_debug()` is one of the many public APIs that are only public because the app used it. I don't remember what it tried to do, but it was very weird.

[1]: https://codesearch.debian.net/search?perpkg=1&q=%5CbPKCS12_get_attr%5Cb

**Comment by richsalz** [comment]
Unfortunately, Akamai has customers that still pay us for SSLv3 but we're hoping to remove it completely by early 2025.
I forgot about the name "Valhalla". Hope you played "The Immigrant Song" often during that time. :)

I will remove the other four and create a PR, tweak the find-doc-nits script, and then get back to the rm-vms PR's.

**Comment by richsalz** [comment]
did what we can for now.
